version: '3.8'

services:
  regression:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest --version"
    working_dir: /usr/workspace
#    environment:
#      - LOGIN=${LOGIN}
#      - PASSWORD=${PASSWORD}