name: Running API tests for ASK

on:
  push
## ${{ secrets.SuperSecret }}
env:
  db_user: ${{ secrets.DB_USER }}
  db_pass: ${{ secrets.DB_PASS }}
  db_name: ${{ secrets.DB_NAME }}
  db_port: ${{ secrets.DB_PORT }}
  db_host: ${{ secrets.DB_HOST }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup dependencies
        run: pip install -r requirements.txt
      - name: Run Healthcheckctest
        run: pytest -m tcid02

